const dataNotice = [
    {
        id: '000000001',
        avatar: 'https://gw.alipayobjects.com/zos/rmsportal/ThXAXghbEsBCCSDihZxY.png',
        title: 'Title 1',
        datetime: '2017-08-09',
        type: 'notification',
    },
    {
        id: '000000002',
        avatar: 'https://gw.alipayobjects.com/zos/rmsportal/OKJXDXrmkNshAMvwtvhu.png',
        title: 'Title 2',
        datetime: '2017-08-08',
        type: 'notification',
    },
    {
        id: '000000003',
        avatar: 'https://gw.alipayobjects.com/zos/rmsportal/kISTdvpyTAhtGxpovNWd.png',
        title: 'Title 3',
        datetime: '2017-08-07',
        read: true,
        type: 'notification',
    },
    {
        id: '000000004',
        avatar: 'https://gw.alipayobjects.com/zos/rmsportal/GvqBnKhFgObvnSGkDsje.png',
        title: 'Title 4',
        datetime: '2017-08-07',
        type: 'notification',
    },
    {
        id: '000000005',
        avatar: 'https://gw.alipayobjects.com/zos/rmsportal/ThXAXghbEsBCCSDihZxY.png',
        title: 'Title 5',
        datetime: '2017-08-07',
        type: 'notification',
    },
    {
        id: '000000006',
        avatar: 'https://gw.alipayobjects.com/zos/rmsportal/fcHMVNCjPOsbUGdEduuv.jpeg',
        title: 'Title 5',
        description: 'Descriptions 1',
        datetime: '2017-08-07',
        type: 'message',
        clickClose: true,
    },
    {
        id: '000000007',
        avatar: 'https://gw.alipayobjects.com/zos/rmsportal/fcHMVNCjPOsbUGdEduuv.jpeg',
        title: 'Title 6',
        description: 'Descriptions 2',
        datetime: '2017-08-07',
        type: 'message',
        clickClose: true,
    },
    {
        id: '000000008',
        avatar: 'https://gw.alipayobjects.com/zos/rmsportal/fcHMVNCjPOsbUGdEduuv.jpeg',
        title: 'Title 7',
        description: 'Descriptions 3',
        datetime: '2017-08-07',
        type: 'message',
        clickClose: true,
    },
    {
        id: '000000009',
        title: 'Title 8',
        description: 'Descriptions 4 2017-01-12 20:00 hehee',
        extra: 'Extra Minvoice',
        status: 'todo',
        type: 'event',
    },
    {
        id: '000000010',
        title: 'Title 9',
        description: 'Descriptions 5 2017-01 đến 2017-01-07 hoho',
        extra: 'Extra NAMPV',
        status: 'urgent',
        type: 'event',
    },
    {
        id: '000000011',
        title: 'Title 10',
        description: 'Hihi 2017-01-09 Descriptions 6',
        extra: 'extra 8 ',
        status: 'doing',
        type: 'event',
    },
    {
        id: '000000012',
        title: 'ABCD Title 11',
        description: 'Descriptions 8 2017-01 2017-01-07 Go to',
        extra: 'extra hahaa',
        status: 'processing',
        type: 'event',
    },
];
module.exports = { dataNotice };